name: Cloud Run Production Deployment
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Clone repository with submodules
        uses: ./.github/actions/clone_repo
        with:
          app-id: ${{ secrets.GH_APP_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          ref: 'main'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Authenticate to Google Cloud
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT }} | gcloud auth activate-service-account --key-file=-
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/playground-app-hosting

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy playground-app-hosting \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/playground-app-hosting \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated
