name: Cloud Run Production Deployment

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  REGION: asia-northeast1
  REPO_NAME: playground-app-hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Composite actionを使用するために必要
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clone repository with submodules
        uses: ./.github/actions/clone_repo
        with:
          app-id: ${{ secrets.GH_APP_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          ref: 'main'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit \
            --revision=${{ github.sha }} \
            --config=cloudbuild.yaml \
            --region=${{ env.REGION }}
